//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSPublicApp.Infrastructure.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITSPublicApp.Infrastructure.Global.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your case has been successfully submitted to Innovate! &lt;br /&gt;&lt;br /&gt;The INN Reference Number is {0} &lt;br /&gt;&lt;br /&gt;Thank you..
        /// </summary>
        public static string CaseSubmittedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("CaseSubmittedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login or Password Entered.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login or Password Entered.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of 5 attempts logged..
        /// </summary>
        public static string LoginAttempts {
            get {
                return ResourceManager.GetString("LoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authorisations found.
        /// </summary>
        public static string NoAuthorisationFound {
            get {
                return ResourceManager.GetString("NoAuthorisationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existing Patients Initial Assessments found.
        /// </summary>
        public static string NoInitialAssessmentFound {
            get {
                return ResourceManager.GetString("NoInitialAssessmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No New Patients found.
        /// </summary>
        public static string NoNewPatientsFound {
            get {
                return ResourceManager.GetString("NoNewPatientsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Next Assessment found.
        /// </summary>
        public static string NoNextAssessmentFound {
            get {
                return ResourceManager.GetString("NoNextAssessmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stopped Cases found.
        /// </summary>
        public static string NoStoppedCasesFound {
            get {
                return ResourceManager.GetString("NoStoppedCasesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password Expired.
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security purposes, your account has been locked. Please contact your administrator.
        /// </summary>
        public static string UserIsLockMessage {
            get {
                return ResourceManager.GetString("UserIsLockMessage", resourceCulture);
            }
        }
    }
}
