//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWebApp.ITSService.FinanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CaseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseID {
            get {
                return this.CaseIDField;
            }
            set {
                if ((this.CaseIDField.Equals(value) != true)) {
                    this.CaseIDField = value;
                    this.RaisePropertyChanged("CaseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComplete {
            get {
                return this.IsCompleteField;
            }
            set {
                if ((this.IsCompleteField.Equals(value) != true)) {
                    this.IsCompleteField = value;
                    this.RaisePropertyChanged("IsComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedCaseInvoicePatientReferrer", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class PagedCaseInvoicePatientReferrer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ITSWebApp.ITSService.FinanceService.CaseInvoicePatientReferrer[] CaseInvoicePatientReferrerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITSWebApp.ITSService.FinanceService.CaseInvoicePatientReferrer[] CaseInvoicePatientReferrer {
            get {
                return this.CaseInvoicePatientReferrerField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseInvoicePatientReferrerField, value) != true)) {
                    this.CaseInvoicePatientReferrerField = value;
                    this.RaisePropertyChanged("CaseInvoicePatientReferrer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseInvoicePatientReferrer", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class CaseInvoicePatientReferrer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CaseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseReferrerReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceActualAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OutstandingAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrerContactFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrerContactLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReferrerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrerMainContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrerMainContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalAmountReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseID {
            get {
                return this.CaseIDField;
            }
            set {
                if ((this.CaseIDField.Equals(value) != true)) {
                    this.CaseIDField = value;
                    this.RaisePropertyChanged("CaseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseReferrerReferenceNumber {
            get {
                return this.CaseReferrerReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseReferrerReferenceNumberField, value) != true)) {
                    this.CaseReferrerReferenceNumberField = value;
                    this.RaisePropertyChanged("CaseReferrerReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceActualAmount {
            get {
                return this.InvoiceActualAmountField;
            }
            set {
                if ((this.InvoiceActualAmountField.Equals(value) != true)) {
                    this.InvoiceActualAmountField = value;
                    this.RaisePropertyChanged("InvoiceActualAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OutstandingAmount {
            get {
                return this.OutstandingAmountField;
            }
            set {
                if ((this.OutstandingAmountField.Equals(value) != true)) {
                    this.OutstandingAmountField = value;
                    this.RaisePropertyChanged("OutstandingAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferrerContactFirstName {
            get {
                return this.ReferrerContactFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferrerContactFirstNameField, value) != true)) {
                    this.ReferrerContactFirstNameField = value;
                    this.RaisePropertyChanged("ReferrerContactFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferrerContactLastName {
            get {
                return this.ReferrerContactLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferrerContactLastNameField, value) != true)) {
                    this.ReferrerContactLastNameField = value;
                    this.RaisePropertyChanged("ReferrerContactLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferrerID {
            get {
                return this.ReferrerIDField;
            }
            set {
                if ((this.ReferrerIDField.Equals(value) != true)) {
                    this.ReferrerIDField = value;
                    this.RaisePropertyChanged("ReferrerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferrerMainContactEmail {
            get {
                return this.ReferrerMainContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferrerMainContactEmailField, value) != true)) {
                    this.ReferrerMainContactEmailField = value;
                    this.RaisePropertyChanged("ReferrerMainContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferrerMainContactPhone {
            get {
                return this.ReferrerMainContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferrerMainContactPhoneField, value) != true)) {
                    this.ReferrerMainContactPhoneField = value;
                    this.RaisePropertyChanged("ReferrerMainContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalAmountReceived {
            get {
                return this.TotalAmountReceivedField;
            }
            set {
                if ((this.TotalAmountReceivedField.Equals(value) != true)) {
                    this.TotalAmountReceivedField = value;
                    this.RaisePropertyChanged("TotalAmountReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceCollectionActionUserName", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class InvoiceCollectionActionUserName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateofActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FollowUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceCollectionActionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateofAction {
            get {
                return this.DateofActionField;
            }
            set {
                if ((this.DateofActionField.Equals(value) != true)) {
                    this.DateofActionField = value;
                    this.RaisePropertyChanged("DateofAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FollowUpDate {
            get {
                return this.FollowUpDateField;
            }
            set {
                if ((this.FollowUpDateField.Equals(value) != true)) {
                    this.FollowUpDateField = value;
                    this.RaisePropertyChanged("FollowUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceCollectionActionID {
            get {
                return this.InvoiceCollectionActionIDField;
            }
            set {
                if ((this.InvoiceCollectionActionIDField.Equals(value) != true)) {
                    this.InvoiceCollectionActionIDField = value;
                    this.RaisePropertyChanged("InvoiceCollectionActionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoicePaymentUserName", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class InvoicePaymentUserName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdjustedPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BACSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoicePaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoicePaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdjustedPayment {
            get {
                return this.AdjustedPaymentField;
            }
            set {
                if ((this.AdjustedPaymentField.Equals(value) != true)) {
                    this.AdjustedPaymentField = value;
                    this.RaisePropertyChanged("AdjustedPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BACS {
            get {
                return this.BACSField;
            }
            set {
                if ((object.ReferenceEquals(this.BACSField, value) != true)) {
                    this.BACSField = value;
                    this.RaisePropertyChanged("BACS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoicePaymentDate {
            get {
                return this.InvoicePaymentDateField;
            }
            set {
                if ((this.InvoicePaymentDateField.Equals(value) != true)) {
                    this.InvoicePaymentDateField = value;
                    this.RaisePropertyChanged("InvoicePaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoicePaymentID {
            get {
                return this.InvoicePaymentIDField;
            }
            set {
                if ((this.InvoicePaymentIDField.Equals(value) != true)) {
                    this.InvoicePaymentIDField = value;
                    this.RaisePropertyChanged("InvoicePaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceCollectionAction", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class InvoiceCollectionAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateofActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FollowUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceCollectionActionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateofAction {
            get {
                return this.DateofActionField;
            }
            set {
                if ((this.DateofActionField.Equals(value) != true)) {
                    this.DateofActionField = value;
                    this.RaisePropertyChanged("DateofAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FollowUpDate {
            get {
                return this.FollowUpDateField;
            }
            set {
                if ((this.FollowUpDateField.Equals(value) != true)) {
                    this.FollowUpDateField = value;
                    this.RaisePropertyChanged("FollowUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceCollectionActionID {
            get {
                return this.InvoiceCollectionActionIDField;
            }
            set {
                if ((this.InvoiceCollectionActionIDField.Equals(value) != true)) {
                    this.InvoiceCollectionActionIDField = value;
                    this.RaisePropertyChanged("InvoiceCollectionActionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoicePayment", Namespace="http://schemas.datacontract.org/2004/07/ITSService.DTO")]
    [System.SerializableAttribute()]
    public partial class InvoicePayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdjustedPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BACSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoicePaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoicePaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdjustedPayment {
            get {
                return this.AdjustedPaymentField;
            }
            set {
                if ((this.AdjustedPaymentField.Equals(value) != true)) {
                    this.AdjustedPaymentField = value;
                    this.RaisePropertyChanged("AdjustedPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BACS {
            get {
                return this.BACSField;
            }
            set {
                if ((object.ReferenceEquals(this.BACSField, value) != true)) {
                    this.BACSField = value;
                    this.RaisePropertyChanged("BACS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoicePaymentDate {
            get {
                return this.InvoicePaymentDateField;
            }
            set {
                if ((this.InvoicePaymentDateField.Equals(value) != true)) {
                    this.InvoicePaymentDateField = value;
                    this.RaisePropertyChanged("InvoicePaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoicePaymentID {
            get {
                return this.InvoicePaymentIDField;
            }
            set {
                if ((this.InvoicePaymentIDField.Equals(value) != true)) {
                    this.InvoicePaymentIDField = value;
                    this.RaisePropertyChanged("InvoicePaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITSService.FinanceService.IFinanceService")]
    public interface IFinanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/AddInvoice", ReplyAction="http://tempuri.org/IFinanceService/AddInvoiceResponse")]
        int AddInvoice(ITSWebApp.ITSService.FinanceService.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetOutstandingInvoicesCasePatientReferrer", ReplyAction="http://tempuri.org/IFinanceService/GetOutstandingInvoicesCasePatientReferrerRespo" +
            "nse")]
        ITSWebApp.ITSService.FinanceService.PagedCaseInvoicePatientReferrer GetOutstandingInvoicesCasePatientReferrer(int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetInvoiceByInvoiceID", ReplyAction="http://tempuri.org/IFinanceService/GetInvoiceByInvoiceIDResponse")]
        ITSWebApp.ITSService.FinanceService.Invoice GetInvoiceByInvoiceID(int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetInvoiceCollectionActionByInvoiceID", ReplyAction="http://tempuri.org/IFinanceService/GetInvoiceCollectionActionByInvoiceIDResponse")]
        ITSWebApp.ITSService.FinanceService.InvoiceCollectionActionUserName[] GetInvoiceCollectionActionByInvoiceID(int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetInvoicePaymentByInvoiceID", ReplyAction="http://tempuri.org/IFinanceService/GetInvoicePaymentByInvoiceIDResponse")]
        ITSWebApp.ITSService.FinanceService.InvoicePaymentUserName[] GetInvoicePaymentByInvoiceID(int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/AddInvoiceCollectionAction", ReplyAction="http://tempuri.org/IFinanceService/AddInvoiceCollectionActionResponse")]
        int AddInvoiceCollectionAction(ITSWebApp.ITSService.FinanceService.InvoiceCollectionAction invoiceCollectionAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/AddInvoicePayment", ReplyAction="http://tempuri.org/IFinanceService/AddInvoicePaymentResponse")]
        int AddInvoicePayment(ITSWebApp.ITSService.FinanceService.InvoicePayment invoicePayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/UpdateInvoiceIsCompleteByInvoiceID", ReplyAction="http://tempuri.org/IFinanceService/UpdateInvoiceIsCompleteByInvoiceIDResponse")]
        int UpdateInvoiceIsCompleteByInvoiceID(bool isComplete, int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetOutstandingInvoicesCasePatientReferrerByInv" +
            "oiceID", ReplyAction="http://tempuri.org/IFinanceService/GetOutstandingInvoicesCasePatientReferrerByInv" +
            "oiceIDResponse")]
        ITSWebApp.ITSService.FinanceService.CaseInvoicePatientReferrer GetOutstandingInvoicesCasePatientReferrerByInvoiceID(int invoiceID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceServiceChannel : ITSWebApp.ITSService.FinanceService.IFinanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceServiceClient : System.ServiceModel.ClientBase<ITSWebApp.ITSService.FinanceService.IFinanceService>, ITSWebApp.ITSService.FinanceService.IFinanceService {
        
        public FinanceServiceClient() {
        }
        
        public FinanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddInvoice(ITSWebApp.ITSService.FinanceService.Invoice invoice) {
            return base.Channel.AddInvoice(invoice);
        }
        
        public ITSWebApp.ITSService.FinanceService.PagedCaseInvoicePatientReferrer GetOutstandingInvoicesCasePatientReferrer(int skip, int take) {
            return base.Channel.GetOutstandingInvoicesCasePatientReferrer(skip, take);
        }
        
        public ITSWebApp.ITSService.FinanceService.Invoice GetInvoiceByInvoiceID(int invoiceID) {
            return base.Channel.GetInvoiceByInvoiceID(invoiceID);
        }
        
        public ITSWebApp.ITSService.FinanceService.InvoiceCollectionActionUserName[] GetInvoiceCollectionActionByInvoiceID(int invoiceID) {
            return base.Channel.GetInvoiceCollectionActionByInvoiceID(invoiceID);
        }
        
        public ITSWebApp.ITSService.FinanceService.InvoicePaymentUserName[] GetInvoicePaymentByInvoiceID(int invoiceID) {
            return base.Channel.GetInvoicePaymentByInvoiceID(invoiceID);
        }
        
        public int AddInvoiceCollectionAction(ITSWebApp.ITSService.FinanceService.InvoiceCollectionAction invoiceCollectionAction) {
            return base.Channel.AddInvoiceCollectionAction(invoiceCollectionAction);
        }
        
        public int AddInvoicePayment(ITSWebApp.ITSService.FinanceService.InvoicePayment invoicePayment) {
            return base.Channel.AddInvoicePayment(invoicePayment);
        }
        
        public int UpdateInvoiceIsCompleteByInvoiceID(bool isComplete, int invoiceID) {
            return base.Channel.UpdateInvoiceIsCompleteByInvoiceID(isComplete, invoiceID);
        }
        
        public ITSWebApp.ITSService.FinanceService.CaseInvoicePatientReferrer GetOutstandingInvoicesCasePatientReferrerByInvoiceID(int invoiceID) {
            return base.Channel.GetOutstandingInvoicesCasePatientReferrerByInvoiceID(invoiceID);
        }
    }
}
